remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentaci√≥n

nombres: Clara Eliana Ramirez Lopez
submodulo: Moviles 1
periodo: 2023-2
url_foto: img
